name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  COVERAGE_MIN: "70"

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements.dev.txt ]; then pip install -r requirements.dev.txt; fi
          pip install ruff mypy pytest pytest-cov pre-commit

      - name: Pre-commit
        run: pre-commit run -a --show-diff-on-failure

      - name: Ruff
        run: ruff check .

      - name: Mypy
        run: mypy --config-file=mypy.ini app tests

      - name: Pytest with coverage
        run: |
          pytest -q --maxfail=1 --disable-warnings \
            --cov=app --cov-report=xml --cov-report=term-missing \
            --cov-fail-under=${COVERAGE_MIN}

      - name: Upload coverage.xml
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: ignore
